AncientAgeの販売情報登録
coop-mojo/moecoop-data pull request #42
Opened 2020-09-26 08:25 UTC by Helestia

AncientAgeの販売情報の更新を行いました。

下記内容について、修正が必要であれば直しますのでご指示ください、

- ファイル名・エリア名について
  - `各エリア`とまとめて表記しましたが、[wiki](http://moewiki.usamimi.info/index.php?NPC%C8%CE%C7%E4%CA%AA%2FAncient_Age)には`ソレス渓谷、ユグ海岸、ゲオの深淵、シスの天空島、ミトヤの大樹`と表記されています。どのように表現しましょうか？
- アセット`旅の商人`の扱いについて
  - 販売情報としては`オート ベンダー`と同一のようです。別で用意するか、販売員名を加工するか、ご指示いただければと思います。

以上、よろしくお願いいたします。

2020-10-03 13:10 UTC, coop-mojo commented
> - ファイル名・エリア名について 

利用側の利便性を考えると、各エリアごとに個別にデータを作成したほうが良さそうです。
エリアごとにファイルを分けるほうが検証が楽そうなので、ファイルも分けていただけると助かります！

> - アセット`旅の商人`の扱いについて 

これも別データとして用意するほうが扱いやすくなると思うので、分けてください！

2020-10-03 14:40 UTC, Helestia commented
ご指摘の通り修正しました。
もう1点確認です。

- ゲオの深淵とゲオ北東・南・西の扱いについて
それぞれファイルを分けました。ゲオ深淵と1つのファイルに修正するべきであれば再度修正いたします。

以上、コミットログの整理術を学んだほうがいいでしょうか…orz
gitに不慣れで申し訳ないです。

2020-10-03 16:59 UTC, coop-mojo requested changes
ファイルの分け方はこのままで大丈夫です！

ただ、旅の商人は別ファイルに分けてもらってもよろしいですか？
これはアセットの一種なので、各エリアのデータとして置くべきものではなさそうです。

データ構造的には…どうしましょうか…
ちょっと考えてみます。

2020-10-03 16:59 UTC, coop-mojo commented on resource/売店/Ancient/シス天空島.json
> +        "エリア" : "シス天空島",
エリア名は `シスの天空島` でお願いします！([公式サイト](http://moepic.com/sp/sthis/index.html)によるとこの名前が正式っぽい)

2020-10-03 17:29 UTC, coop-mojo commented
> 以上、コミットログの整理術を学んだほうがいいでしょうか…orz

実は PR のコミットログではそれほど深く考えなくても問題ありません。
というのも、PR のマージ側に `Squash and Merge` (PR 内のコミットを全部まとめて 1 コミットに変換してからマージ)というオプションがあるので、Squash and Merge してしまえば皆同じなのです。

---
一般的な話だと、プロジェクトごとに細部は違うのでケースバイケース…という結論になる気がします。
他のプロジェクトに PR を投げる場合の、ある程度普遍的そうな指針としては、
- 1コミットにつき1変更
  - 例えば、内容に関する変更とインデントの変更はちゃんと別のコミットにして、PR の単位としても分けておく、など
- 不明な場合はとりあえず聞いてみる
  - せっかく PR 作って投げたのに、やっぱり別方針がいい、とか言われてしまうと投げた方の心が萎えてしまうので…
  - 例えば、まず Issue で「この問題解決するための PR をこういう方針で作ろうと思うんだけどどう思う？」とか聞いて反応を待ってみるとか
    - 他の実装方法がある場合、その方式を取った場合の利点・欠点や、方針としては採用しない理由などを触れておくと、返答側の判断材料が増えるので良いと思います。
    - 難しそうに見えますが、例えば「こちらの方が変更行数が少ない or 実装が単純」も判断理由としては十分だと思います。
- `CONTRIBUTING.md` を確認する
  - PR 用のコミットの作成方法やテスト方法などが書かれたファイルが提供されていることも多いので、リポジトリに置いてある場合は参照するのがいいと思います！！！(moecoop-data にはそんなものはなかった)
  - コミットメッセージの流儀はプロジェクトごとに異なるので、`CONTRIBUTING.md` や、同プロジェクトの他のコミットを確認するのがいいです。
- まともなプロジェクトならちゃんとレビューが入るはずなので、深く考えずにとりあえずぶん投げてみる、という方針でもいいかもしれません。
---
自分のプロジェクトの場合は、自分が分かれば何でもいいと思います！
モチベ維持できるのが大正義なので！

2020-10-04 01:30 UTC, Helestia commented
レビューありがとうございます。ゲオは途中で略名だと気づいたのですが、天空島は気づいてませんでした…

旅の商人はファイル名を`旅の商人.json`とし、エリアをいったん`アセット`と修正しました。
ファイル名はともかく、エリアはもう少し最適な文言がありそうですが、私のボキャブラリのなさが…

たびたび申し訳ありません。引き続きレビューをお願いいたします。

2020-10-04 01:37 UTC, Helestia commented
コミットログについて、色々教えていただきありがとうございます。

> 1コミット1変更
やはりそういう方針がいいのですか。

出来ないよりはできたほうがいいとは思いますので、`rebase`や`reset`なんかについて勉強してきます。
教えていただきありがとうございました。

2020-10-05 19:41 UTC, merged

2020-10-05 19:45 UTC, coop-mojo commented
Thx!

> 旅の商人はファイル名を旅の商人.jsonとし、エリアをいったんアセットと修正しました。

これは他にうまいやり方も思いつかないので、これでいいと思います。

> 出来ないよりはできたほうがいいとは思いますので、`rebase`や`reset`なんかについて勉強してきます。

reset.. 数回くらいしか(しかもググりながらしか)使ったことないですね…
`push`, `pull` など以外で使用頻度がそれなりに高くて便利なのは、`branch`, `checkout`, `stash`, `bisect`, `blame` くらいでしょうか。

特に`bisect` は、テスト環境がある程度整っている状態だとかなり便利ですね(エンバグしたコミットの自動絞り込みができる)。