WarAgeの販売情報登録
coop-mojo/moecoop-data pull request #43
Opened 2020-09-26 10:13 UTC by Helestia

WarAgeのNPC販売情報を作成しました。

下記内容について、ご確認をお願いします。

- 全体的なファイル構成について
  - どのようにすればいいか判断つきませんでした。よろしければご指示ください。
- CC/DAの販売情報について
  - 件数が少ないこともあり、ファイルを1つにまとめ、各販売物に備考テキストを付与しました。記載方法がこれでいいか確認してください。
- 奇跡販売物について
  - 販売NPC名が同名で3名
    - `古代モラ人`ぇ…
    - `古代モラ人１`等、ユニーク名にする必要があるのでしたらご指示ください。
      - Pre/War等のNPC販売者全体としてユニークに保持するのでしたら、名称の後ろに何か付けます。`ステラ (アルビーズの森)`とか既存でもすでにそのような管理をされているのですかね？
  - ファイル構造
    - 城下町ビスク／エルガディン王国にそれぞれ登録したほうがよければご指示ください。また、備考テキストについても指示があれば修正いたします。

以上、レビューお願いいたします。

2020-10-03 13:01 UTC, coop-mojo commented
反応遅れてすみません！とりあえず全体方針関係の返信です！

> 全体的なファイル構成について 

ファイル構成は PR のもので問題ないと思います！

> CC/DAの販売情報について

悩ましい点が多いため暫定対応ですが… (War Age は全然詳しくないので、間違っていたらご指摘ください)
- 各備考欄の `WarAgeのCC/DA条件pop` ですが、これはおそらく[公式サイト](https://moepic.com/avg/warage.php#07)にある、`制圧時の恩恵` のことでいいのですよね？拠点制圧されている・いないで NPC 自体の pop 状況が変わるのであれば、備考欄の位置を変更するほうがいいと思います。また、以下のように pop 条件を明記するほうがいいと思います。以下が変更案です。
    ```json
    {
        "名前": "アマゾネス グローサー",
        "時代" : "War Age",
        "エリア" : "ヴァルグリンドの巣穴",
        "販売情報": {
            ...
        },
        "備考": "BSG または EGL による拠点制圧時のみ pop"  # 備考欄の位置を変更+pop 条件を明記
    }
    ```

> 奇跡販売物について

>- 販売NPC名が同名で3名

どうしましょうか…
とりあえず、JSON 的には同名でも問題ないため、アプリ側に扱いは任せる(つまり、データ構造としては PR のまま)というのでいかがでしょう？
見た目に違いがある場合、カッコで服装を補足するのもいいかもしれません(検証が必要になりますが…)

> ステラ (アルビーズの森)とか既存でもすでにそのような管理をされているのですかね？

これは知恵袋(アプリ)側の処理の都合でこうなっていました。現状だとエリアフィールドがあるので、単に `ステラ` にしても問題ないかもしれません(が、この PR の範囲外)。

> - ファイル構造
`城下町ビスク` と `エルガディン王国` それぞれで作成していただけると助かります！ 
`城下町ビスクorエルガディン王国` だとアプリ側で文字列のパースが必要になるため、取り回しにくくなりそうです。

その他細かい部分は直接該当コード部分にコメントします！

2020-10-03 13:06 UTC, coop-mojo requested changes

2020-10-03 13:06 UTC, coop-mojo commented on resource/売店/war/CCandDA.json
> +]
末尾に改行追加をお願いします！

2020-10-03 13:06 UTC, coop-mojo commented on resource/売店/war/奇跡.json
> +                "備考": "奇跡発生時、発生勢力の拠点に出現"
各アイテムの備考ではなく、販売人の備考欄に移動お願いします！

2020-10-03 14:00 UTC, Helestia commented
ご回答ありがとうございます。そして最終行等何度も指摘させてしまい申し訳ございません…

>> CC/DAの販売情報について

>各備考欄の WarAgeのCC/DA条件pop ですが、これはおそらく公式サイトにある、制圧時の恩恵 のことでいいのですよね？拠点制圧されている・いないで NPC 自体の pop 状況が変わるのであれば、備考欄の位置を変更するほうがいいと思います。また、以下のように pop 条件を明記するほうがいいと思います。

ご指摘の通りです。
拠点の占領状況によってNPCのPOP・及び売買可能な勢力が変わります。
- 軍属未占領時はPOPしません。
- 軍属占領時(ELG/BSQ占領時)にpopし、占領勢力及びNEUが該当勢力に友好がある場合、利用可能となります。

一点確認ですが、販売員の項目自体に備考を付与することは可能なのでしょうか？
現状ではエルビン渓谷の行商人NPCなどのpop時間などが販売物に対して備考が付与されているため、NPCに対して備考を付与することができない構造と考えていました。
もし販売員NPCに対して備考を付与することができるのでしたら、別途Preのエルビン側も修正いたします。

> 奇跡NPCの扱いについて
- 服装
昔warageには私も入り浸ってましたが、残念ながらNメインで動いていたので、販売員の服装とか…覚えてないです；；
JSONデータ構造としては現状配列で管理しているため、同名の販売員が複数名いても問題にはなりませんが…気持ち悪いですよね…

とりあえず明らかに修正が必要な項目についてのみ、修正を行います。

2020-10-03 18:19 UTC, coop-mojo commented
> 一点確認ですが、販売員の項目自体に備考を付与することは可能なのでしょうか？

必要ならば足します！

---

> 現状ではエルビン渓谷の行商人NPCなどのpop時間などが販売物に対して備考が付与されているため

これは単に、エルビンの行商人の場合は、私がアイテムの備考欄に入れるほうが適切だと思ったから、以上の理由はないです！(正しい・間違っている、という客観的な判断に基づいてこうなったわけではなく、私が認識したものをデータ構造にそのまま落としたらこうなった)

ご指摘のある行商人 NPC は、全アイテムの備考欄に `村への移動中限定` がある `行商人 ギリアム` などですよね？ (具体的に pop 時間を記載したものはなかったはず)
ギリアムの場合は移動中以外に村に滞在している場合があり、その場合には何も売ってくれません。
村に滞在している状態を、「ギリアムは販売人ではない」(つまり、ギリアム自身に販売人フラグがある)と捉えるか、「ギリアムは販売する商品がない」(各アイテムに販売可能かどうかのフラグがある)と捉えるかの違いだと思います。
エルビン渓谷のデータの作成時には、私は後者だと感じたため、後者っぽい(つまりアイテム側に備考欄を付ける)データ構造を採用しました。

一方で、今回の War Age の NPC は、販売時以外にはそもそも pop していません(公式サイト中の `各キャンプ地固有のNPCベンダーが配置されます` をそう解釈した)。そのため、私はこれらの NPC の販売状態を「存在するかしないか」 (NPC 自身に販売人フラグがあると捉え、また販売人フラグと出現フラグをほぼ同一視する)と捉えたため、販売員側に備考欄を付けるほうが適切ではないか、と判断しました。
(占領時以外も同 NPC が存在しているのであれば、アイテム側に備考を付与するのが適切だと思います。存在している場合はご指摘ください！)

---
なので、エルビンの行商人に関してはそのままでお願いします！

2020-10-03 18:23 UTC, coop-mojo commented
> - 服装
>   昔warageには私も入り浸ってましたが、残念ながらNメインで動いていたので、販売員の服装とか…覚えてないです；；

それならとりあえず現状のままでいきましょう！

2020-10-04 02:30 UTC, Helestia commented
レビューありがとうございます。
確かにpop時間に記載のあるものはありませんでした。私の勘違いでした。

備考項目について、販売員への備考の場合は販売物ではなく販売員につけるよう修正いたしました。
合わせてどの拠点制圧時にpopするかも記載しました。

奇跡NPCについても、各拠点に記載したうえで、各軍属が奇跡発生時のみpopする旨を記載しました。
以上、たびたびのレビュー申し訳ありませんが、引き続きご確認いただきますようお願いいたします。

2020-10-05 19:47 UTC, coop-mojo approved these changes

2020-10-05 19:47 UTC, merged

2020-10-05 19:47 UTC, coop-mojo commented
Thx!