Issue #25 飲食バフフォルダのスキーマ情報登録
coop-mojo/moecoop-data pull request #84
Opened 2020-10-11 14:30 UTC by Helestia

Issue #25 

お待たせいたしました。
最後のスキーマ登録PRとなります。

- 追加効果
PR #83 で事前に作業させていただいた通り、飲食バフ限定の項目が存在しています。
残念ながら新しい効果が出現した場合はスキーマ側を治すことになると思います。
しかし、これまでの表記ゆれなどの対応から解放されるなら…と思ってしまうのはやはり作業者だからでしょうか。
- buffグループ
`A`-`F`が存在し、`B`,`C`,`D`には上書関係の上下関係があること、それらの調査状況不明を許容するためこのような表記としました。
現状ではスキーマは通りますが、運用上問題が出るようなら今後修正していく形でいいかと思います。

以上、これまでありがとうございました。
クエストを除いた最終PRとなりますが、ご確認をお願いいたします。

2020-10-25 03:57 UTC, coop-mojo requested changes

2020-10-25 03:57 UTC, coop-mojo commented on schemas/飲食バフ.json
> +                    "その他"
バフグループには `"不明"` を足していただけるとありがたいです！

2020-10-25 07:45 UTC, Helestia commented on schemas/飲食バフ.json
> +                    "その他"
すいません、不明は`ワサビ`や`モーション変化`等、A-Fにカテゴライズされないアイテムが現在登録されています。

不明を新設するのでしたら作業しますが、`その他`は別で必要かと思います。
別途名称変更を行うのでしたら該当作業を行いますので、ご指示ください。

2020-10-25 07:51 UTC, Helestia commented on schemas/飲食バフ.json
> +                    "その他"
おっと…不明を「足す」ですね。失礼しました。作業いたします。

2020-10-26 14:59 UTC, coop-mojo approved these changes

2020-10-26 15:00 UTC, merged

2020-10-26 15:00 UTC, coop-mojo commented
Thanks!